services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:application
    preDeployCommand: cd backend && python manage.py migrate && python create_admin.py && python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: django-insecure-f!o5v*oy7#n35$g-=9wg_zh^rrib=y8=7@(q%^=bj=@^545#xe
      - key: DATABASE_URL
        value: postgresql://test_db_12oo_user:oVV4Qcqv7dK6wGeSQGnKcoCAzlvvu53V@dpg-d0all715pdvs73brneu0-a.oregon-postgres.render.com/test_db_12oo

