services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:application
    preDeployCommand: python manage.py migrate  # ← これを追加！
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: あなたのSECRET_KEY
